### ISSUE TITLE
Blank page after installation

### ISSUE THREAD

**Issue by gelavat** [unicate/pico-bulma#1]
Hello.
I have followed your "Download & Install" section, but doing this there is only a blank page displayed on the website.
I installed successfully other themes, but not this one.

Can you please tell me how to solve this issue?

I am using latest Pico CMS version and your latest bulma sources to date.

**Comment by unicate** [comment]
Hi

I just tried with the latest Pico version and I worked fine.

Maybe my description is misleading. In standard Pico installations you have to place the bulma folder under themes/, right beside the default folder. (NOT public/themes like I mentioned in the ReadMe. Thats only correct if you use my GIT-Project.)

Have you checked your config.yml ?
theme: bulma  

I hope this helps. Otherwise please let me know if you see errors in the server logs or the Network-Tab in Browser.

Kind regards

**Comment by gelavat** [comment]
Hello.

Thank you. config.yml was correct.
Yes, it seems that the installation doc needs some update. It is probably good to have two separate installation sections for both things.

I managed to install it this way with the zip file:
- Copy pico-bulma-master/public/themes/bulma -> /themes/bulma
- Copy pico-bulma-master/public/content -> /content (after backup)
- Edit "/config/config.yml" and put this line by replacing existing one: "theme: bulma"
- You can ignore the assets, dist, plugins, sass and config directories.

Customization:
- Edit the first page big text phrase in "/content/_meta.md" in the "Tagline" line. The logo can also be edited in this same section


Could you please update the doc with this info? I think it would make it much clearer.
Also, I think that a Customization quick user manual would be needed to know how to use this theme and add sections, edit text and menus, and so on... I added the first one only.
