### ISSUE TITLE
Readme.md update with installation and customization sections

### ISSUE THREAD

**Issue by gelavat** [unicate/pico-bulma#3]
Hello.

As I faced some issues to install the nice Bulma theme, I would like to suggest changing the readme.md file by putting this:

**Installation:**

•	Copy pico-bulma-master/public/themes/bulma -> /themes/bulma
•	Copy pico-bulma-master/public/content -> /content (after backup)
•	Edit "/config/config.yml" and put this line by replacing previous one: "theme: bulma"
•	You can ignore the dist, plugins, sass and config directories.

**Customization:**

•	The ‘Bulma’ top left logo can be changed in the ‘/content/_meta.md’ file in the ‘Logo’ field. This logo will show up for all *.md pages in ‘/content’.
•	The ‘Welcome’ and ‘Details’ buttons at the top are the ‘*.md’ files present in ‘/content’ and it is their ‘Title’ field in the YAML header at the top (separated with dashes).
•	Edit the first page big text phrase under the site title in ‘/content/_meta.md’ in the ‘Tagline’ field.
•	Change the ‘Github’ and ‘packagist’ buttons in the ‘/theme/bulma/index.twig’ file.
•	Change the ‘Repositories’, ‘John Smith’ and ‘Password’ sections in the ‘/theme/bulma/index.twig’ file. These will be present on each *.md page in ‘/content’ if the ‘Template’ YAML field indicates ‘index’. Else you can define there the ‘sub’ template that will not show them.
•	Change the colors in variables.css and style.css files in the '/theme/bulma/css' directory.

----

This will surely help other quite novice people to install the theme properly and know quickly how to change the fields/contents rather than searching a long time how to do it.

Is that possible please?

**Comment by mayamcdougall** [comment]
Hello from the Pico project @unicate. 👋🏻

I just wanted to chime in with a few things.  First of all, we recently deprecated the Themes Wiki page, so I went through and added all themes that were wiki-only to our gallery at [PicoCMS.org](https://picocms.org/themes/), which included Bulma (which is probably why it's getting some attention).

I also had an issue with installation because apparently I was too dense to read the readme properly. 🤦🏻‍♀️

I didn't realize there was a `dist` zip and just cloned the whole repo.  As you can imagine, it took me a few minutes on the command line to figure out what the actual directory structure was and where the theme folder ended up. 😅

I actually didn't even realize that the instructions said to use `dist/bulma.zip` until *just now*.

I don't know what to say about this.  It's entirely on me for not reading more thoroughly.

I didn't use your whole project because I was using my existing Pico install to take screenshots of many different themes for uploading to the gallery.

So when I saw `composer`, `npm`, and `gulp`, mentioned in the readme, I just kind of skimmed the whole thing without realizing the pre-configured download was above that. 🤦🏻‍♀️

I think most Pico users are probably also expecting a single theme folder they can grab and chuck in Pico without much thought.  I realize that in this case though, that would go against the whole idea of your Bulma port.

Anyway.  Nothing I can really suggest that you should change.  Just wanted to provide my perspective on this as well, and let you know that your theme was moved from the wiki to the gallery.

No matter what, there will *always* be those that have difficulty because they didn't read the readme (well enough, or at all).  And apparently this time I'm guilty of it too. 😓

**Comment by unicate** [comment]
Hello @mayamcdougall  & Pico Project

Thank you for adding my theme to the gallery.

I really appreciate your feedback and I understand your point.

The problem might be that I have mixed a few things in my repo.
Actually it is all in one: theme, theme-generator and my personal Pico starter project.
That can be confusing for others...

So I guess best thing would be to split up the repo. 
I will leave the theme-part in the current repo, that your links will stay valid and move the other parts to a new repo.

Hope that helps also others to easily use Pico and the Bulma theme.

**Comment by unicate** [comment]
Hi @gelavat and @mayamcdougall 

I have completely restructured the project and removed all the PHP parts.
(Structure is now similiar to [astral-pico](https://github.com/mayamcdougall/astral-pico) by @mayamcdougall )

So now it's clearly just the Bulma theme! No more starter project or boilerplate. Therefore the whole download and installation process should be much simpler and easier to understand.

The documentation is also updated.

**Comment by gelavat** [comment]
Thank you very much for that work @unicate! And thanks for providing this theme. Ideally I should try to install it again and maybe provide corrected installation instructions as a PR.

**Comment by mayamcdougall** [comment]
> I have completely restructured the project and removed all the PHP parts.

Oh, wow. 😳

I can't stress enough how you *really* didn't have to do that!

It looks good though.  This layout seems a lot cleaner and more straightforward to deploy. 👍🏻

---

While you're at it, is there anything you'd want me to change about the [Gallery Entry](https://picocms.org/themes/#entry-bulma)?

There's usually a "submission" process where you'd get to supply all the information in the blurb, the screenshots, etc.  Since I was migrating all the wiki-only themes myself, I mostly worked off of ReadMe descriptions, etc, for them.

If something looks off, let me know and I can edit it.

Also, I put the "By" line down as a theme "Port", since the theme is based on the Bulma framework... but I'm unfamiliar with Bulma, so I don't actually *know* what came from them and what you wrote. I was just guessing. 😅

So, if you feel this is inaccurate, it can be changed.  We don't really have a clear distinction or criteria separating "ports" from "original" themes, it's just there to provide extra information to the user.

Pretty much everything is kind of "MIT soup" on some level anyway, but I try to give credit where credit is due. 😂

---

And again, thanks for updating your repo. ❤️

We don't usually get much feedback from our users unless something is *extra* broken, but @gelavat has been shedding some light recently on some paper cuts new users might experience. 😅

**Comment by unicate** [comment]
@mayamcdougall your welcome :-)

I have updated the description of my repo. Maybe you like to change that in the gallery as well. It's very simple now. :-)

`Pico Bulma - A lightweight Bulma theme for Pico CMS. `

Yes "Port" is fine. I  just integrated the existing Bulma framework into Pico and made some template, style and build stuff.

Thank you for your great work with PicoCMS.  👍🏻 👍🏻 👍🏻

**Comment by mayamcdougall** [comment]
Alright, sounds good.  I'm going to replace the original paragraph:
>This project basically provides a Bulma-Theme and starter project for Pico CMS. It can be used as foundation to build your own customized Bulma themes for Pico CMS.

with that tagline instead.

I'm working on some overall improvements to the themes gallery right now, so the changes might not land for a few days.

(It'll also be replaced in the hover description, but my current redesign isn't actually using those for anything anymore. P=)

> Thank you for your great work with PicoCMS. 👍🏻 👍🏻 👍🏻

And @PhrozenByte deserves any and all credit for PicoCMS (tagging for the mention).  I mostly just do the community and website stuff. 😉

**Comment by unicate** [comment]
Issue was fixed with the clean-up of the repo. Therefore I close the issue.
